openapi: 3.0.2
info:
  title: Bk task API
  description: Bk task API Documentation
  version: 0.1.0
servers:
  - url: /api
    description: Bk task server for development
paths:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
  /dashboard/login:
    post:
      summary: Login
      operationId: post-auth-login
      responses:
        '200':
          description: OK
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                email:
                  example: admin@admin.com
                password:
                  example: password
            examples:
              example:
                value:
                  email: user email
                  password: password
      tags:
        - Admin Authentication
      x-internal: true
      description: ''
    parameters: []
  /dashboard/schools:
    get:
      summary: returns a list of schools
      tags:
        - School
      responses: {}
      operationId: get-dashboard-schools
    post:
      summary: Create a new school
      operationId: post-dashboard-schools
      responses:
        '200':
          description: OK
      requestBody:
        content:
          application/json:
            schema:
              description: ''
              type: object
              properties:
                name:
                  type: string
                  minLength: 1
              required:
                - name
              x-examples:
                example-1:
                  name: name test
            examples:
              example:
                value:
                  name: string
      tags:
        - School
  '/dashboard/schools/{school}':
    parameters:
      - schema:
          type: string
        name: school
        in: path
        required: true
    get:
      summary: Return a school
      tags:
        - School
      responses: {}
      operationId: get-dashboard-schools-school
    patch:
      summary: Update a school
      operationId: patch-dashboard-schools-school
      responses:
        '200':
          description: OK
      tags:
        - School
      requestBody:
        content:
          application/json:
            schema:
              description: ''
              type: object
              properties:
                name:
                  type: string
                  minLength: 1
              required:
                - name
              x-examples:
                example-1:
                  name: update name
            examples:
              example:
                value:
                  name: string
    delete:
      summary: Delete a school
      operationId: delete-dashboard-schools-school
      responses:
        '200':
          description: OK
      tags:
        - School
  /dashboard/students:
    get:
      summary: returns a list of students
      tags:
        - Students
      responses: {}
      operationId: get-dashboard-students
    post:
      summary: ''
      operationId: post-dashboard-students
      responses:
        '200':
          description: OK
      tags:
        - Students
      requestBody:
        content:
          application/json:
            schema:
              description: ''
              type: object
              properties:
                name:
                  type: string
                  minLength: 1
                school_id:
                  type: number
              required:
                - name
                - school_id
              x-examples:
                example-1:
                  name: test name
                  school_id: 1
            examples:
              example:
                value:
                  name: test name
                  school_id: 1
  '/dashboard/students/{student}':
    parameters:
      - schema:
          type: string
        name: student
        in: path
        required: true
    get:
      summary: returns a student
      tags:
        - Students
      responses: {}
      operationId: get-dashboard-students-student
    patch:
      summary: update a student
      operationId: patch-dashboard-students-student
      responses:
        '200':
          description: OK
      tags:
        - Students
      requestBody:
        content:
          application/json:
            schema:
              description: ''
              type: object
              x-examples:
                example-1:
                  name: test name
                  school_id: 1
              properties:
                name:
                  type: string
                  minLength: 1
                school_id:
                  type: number
            examples:
              example:
                value:
                  name: test name
                  school_id: 1
    delete:
      summary: delete a student
      operationId: delete-dashboard-students-student
      responses:
        '200':
          description: OK
      tags:
        - Students
  '/students/{student}':
    parameters:
      - schema:
          type: string
        name: student
        in: path
        required: true
    get:
      summary: returns a student
      tags:
        - Students
      responses: {}
      operationId: get-students-student
components:
  responses:
    ServerError:
      description: Server error
      content:
        application/json:
          schema:
            type: object
            properties:
              message:
                type: string
            example:
              message: Server Error
    TooManyRequest:
      description: Rate limit exceeded error happens when too many requests sent. User must wait one minute.
      content:
        application/json:
          schema:
            type: object
            properties:
              message:
                type: string
            example:
              message: Too Many Attempts.
    InputError:
      description: Input error
      content:
        application/json:
          schema:
            type: object
            properties:
              message:
                type: string
              errors:
                type: object
                items:
                  type: object
                  properties:
                    field_name:
                      type: array
                      items:
                        type: string
            example:
              message: Error message
              errors:
                field_name:
                  - Error message about field
                  - Another error message about field
    Default:
      description: Default response
      content:
        application/json: {}
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
security:
  - bearerAuth: []
tags:
  - name: Admin Authentication
    description: endpoints number 1
  - name: School
    description: endpoints number 5
  - name: Students
    description: endpoints number 6
  - name: default
    description: endpoints number
